In [2]:
import numpy as np

In [4]:
# Creating a list
my_list = [21, 22, 23, 24, 25]

# Creating an array with the same values
my_arr = np.array([21, 22, 23, 24, 25])

# Display the list and array to verify
print("List:", my_list)
print("Array:", my_arr)

List: [21, 22, 23, 24, 25]
Array: [21 22 23 24 25]


In [6]:
# Multiply my_list by 4
list_multiplied = my_list * 4

# Multiply my_arr by 4
array_multiplied = my_arr * 4

# Print the results
print("List multiplied by 4:", list_multiplied)
print("Array multiplied by 4:", array_multiplied)

# Description:
# When you multiply my_list by 4, Python repeats the list four times, 
# creating a longer list. However, when you multiply my_arr (the NumPy array) by 4,
# it performs element-wise multiplication, multiplying each element of the array by 4.

List multiplied by 4: [21, 22, 23, 24, 25, 21, 22, 23, 24, 25, 21, 22, 23, 24, 25, 21, 22, 23, 24, 25]
Array multiplied by 4: [ 84  88  92  96 100]


In [8]:
# Add my_list with itself
list_added = my_list + my_list

# Add my_arr with itself
array_added = my_arr + my_arr

# Attempt to add my_list with my_arr
try:
    list_array_added = my_list + my_arr
except TypeError as e:
    list_array_added = str(e)

# Print the results
print("List + List:", list_added)
print("Array + Array:", array_added)
print("List + Array:", list_array_added)

# Description:
# Adding `my_list` with itself concatenates the list, creating a longer list with repeated elements.
# Adding `my_arr` with itself performs element-wise addition, resulting in each element being doubled.
# Adding `my_list` and `my_arr` directly raises a TypeError because they are different types, and Python 
# does not support addition between lists and NumPy arrays without explicit conversion.

List + List: [21, 22, 23, 24, 25, 21, 22, 23, 24, 25]
Array + Array: [42 44 46 48 50]
List + Array: [42 44 46 48 50]


In [10]:
# Subtract my_list with itself (will raise an error since lists don't support element-wise subtraction)
try:
    list_subtracted = my_list - my_list
except TypeError as e:
    list_subtracted = str(e)

# Subtract my_arr with itself (element-wise subtraction)
array_subtracted = my_arr - my_arr

# Attempt to subtract my_list with my_arr
try:
    list_array_subtracted = my_list - my_arr
except TypeError as e:
    list_array_subtracted = str(e)

# Print the results
print("List - List:", list_subtracted)
print("Array - Array:", array_subtracted)
print("List - Array:", list_array_subtracted)

# Description:
# Subtraction between two lists (e.g., `my_list - my_list`) results in a TypeError, as Python lists do not 
# support element-wise subtraction.
# Subtraction between two NumPy arrays (`my_arr - my_arr`) performs element-wise subtraction, resulting in 
# an array of zeros.
# Subtraction between `my_list` and `my_arr` directly raises a TypeError, as Python doesn't support 
# subtraction between lists and NumPy arrays without explicit conversion.

List - List: unsupported operand type(s) for -: 'list' and 'list'
Array - Array: [0 0 0 0 0]
List - Array: [0 0 0 0 0]


In [14]:
# Subtract my_list with itself (will raise an error since lists don't support element-wise subtraction)
try:
    list_subtracted = my_list - my_list
except TypeError as e:
    list_subtracted = str(e)

# Subtract my_arr with itself (element-wise subtraction)
array_subtracted = my_arr - my_arr

# Attempt to subtract my_list with my_arr
try:
    list_array_subtracted = my_list - my_arr
except TypeError as e:
    list_array_subtracted = str(e)

# Print the results
print("List - List:", list_subtracted)
print("Array - Array:", array_subtracted)
print("List - Array:", list_array_subtracted)

# Description:
# Subtraction between two lists (e.g., `my_list - my_list`) results in a TypeError, as Python lists do not 
# support element-wise subtraction.
# Subtraction between two NumPy arrays (`my_arr - my_arr`) performs element-wise subtraction, resulting in 
# an array of zeros.
# Subtraction between `my_list` and `my_arr` directly raises a TypeError, as Python doesn't support 
# subtraction between lists and NumPy arrays without explicit conversion.

List - List: unsupported operand type(s) for -: 'list' and 'list'
Array - Array: [0 0 0 0 0]
List - Array: [0 0 0 0 0]


In [16]:
# Divide my_list with itself (will raise an error since lists don't support element-wise division)
try:
    list_divided = my_list / my_list
except TypeError as e:
    list_divided = str(e)

# Divide my_arr with itself (element-wise division)
array_divided = my_arr / my_arr

# Attempt to divide my_list by my_arr
try:
    list_array_divided = my_list / my_arr
except TypeError as e:
    list_array_divided = str(e)

# Print the results
print("List / List:", list_divided)
print("Array / Array:", array_divided)
print("List / Array:", list_array_divided)

# Description:
# Division between two lists (e.g., `my_list / my_list`) results in a TypeError, as Python lists do not 
# support element-wise division.
# Division between two NumPy arrays (`my_arr / my_arr`) performs element-wise division, resulting in an 
# array of ones (as each non-zero element divided by itself equals 1).
# Division between `my_list` and `my_arr` directly raises a TypeError, as Python does not support 
# division between lists and NumPy arrays without explicit conversion.

List / List: unsupported operand type(s) for /: 'list' and 'list'
Array / Array: [1. 1. 1. 1. 1.]
List / Array: [1. 1. 1. 1. 1.]


In [18]:
# Description of the difference between a list and an array
description = """
A list in Python is a versatile data structure that can hold elements of different data types but does not support element-wise arithmetic operations directly.
In contrast, a NumPy array is specifically designed for numerical data and supports efficient element-wise operations like addition, subtraction, multiplication, 
and division, making it ideal for mathematical computations.
"""

print(description)


A list in Python is a versatile data structure that can hold elements of different data types but does not support element-wise arithmetic operations directly.
In contrast, a NumPy array is specifically designed for numerical data and supports efficient element-wise operations like addition, subtraction, multiplication, 
and division, making it ideal for mathematical computations.



In [20]:
import numpy as np

def get_second_values(two_d_array):
    # Extracts the second value from each row in the given two-dimensional array
    return [row[1] for row in two_d_array]

# Example array
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

# Call the function and print the result
second_values = get_second_values(arr3)
print("Second values in each row:", second_values)

Second values in each row: [4, 10, 16]


In [22]:
# Description of website section used:
# The "NumPy Array Indexing" section of the W3Schools NumPy tutorial was helpful in understanding how to access specific elements in an array.
# This section provided insights on how to use indexing to extract elements from rows and columns, which helped in writing the function 
# that retrieves the second value in each row of a two-dimensional array.

In [24]:
# Explanation of how to take a nested list and return the second value in each row
"""
To take a nested list and return the second value in each row, you can use a list comprehension that iterates through each sublist 
and accesses the element at index 1. This approach is simple and effective for extracting specific elements from nested lists.
"""

# Example code to demonstrate this
nested_list = [[2, 4, 6], [8, 10, 12], [14, 16, 18]]

# Extract the second value in each row using list comprehension
second_values = [row[1] for row in nested_list]

# Print the result
print("Second values in each row:", second_values)

# Expected output: [4, 10, 16]

Second values in each row: [4, 10, 16]


In [28]:
import numpy as np

def sort_multi_dimensional_array(array):
    """
    Sorts a multi-dimensional array if it is not already sorted.
    Checks each row and sorts the array only if any row is out of order.
    """
    # Check if the array is already sorted by comparing each row
    is_sorted = all((np.array_equal(row, np.sort(row))) for row in array)
    
    if is_sorted:
        print("The array is already sorted.")
        return array
    else:
        print("The array was not sorted, sorting now.")
        sorted_array = np.array([np.sort(row) for row in array])
        return sorted_array

# Example input array
multi_d_array = np.array([[3, 1, 2], [8, 5, 6], [10, 15, 12]])

# Call the function and print the result
sorted_array = sort_multi_dimensional_array(multi_d_array)
print("Sorted array:")
print(sorted_array)

# Expected output:
# "The array was not sorted, sorting now."
# Sorted array:
# [[1 2 3]
#  [5 6 8]
#  [10 12 15]]

The array was not sorted, sorting now.
Sorted array:
[[ 1  2  3]
 [ 5  6  8]
 [10 12 15]]


In [30]:
import numpy as np

# Example 1: Create a NumPy ndarray Object
# Test case 1
arr1 = np.array([1, 2, 3, 4])
print("Example 1 - Test case 1: Create a NumPy ndarray Object")
print(arr1)
print("Type of arr1:", type(arr1))  # Should print <class 'numpy.ndarray'>

# Test case 2
arr2 = np.array([10, 20, 30, 40])
print("\nExample 1 - Test case 2: Create a NumPy ndarray Object")
print(arr2)
print("Type of arr2:", type(arr2))  # Should print <class 'numpy.ndarray'>

# Example 2: Dimensions in Arrays
# 0-D Arrays
zero_d_array = np.array(42)
print("\nExample 2 - 0-D Array")
print("0-D Array:", zero_d_array)
print("Dimensions:", zero_d_array.ndim)  # Should print 0

# 1-D Arrays
one_d_array = np.array([5, 10, 15])
print("\nExample 2 - 1-D Array")
print("1-D Array:", one_d_array)
print("Dimensions:", one_d_array.ndim)  # Should print 1

# 2-D Arrays
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print("\nExample 2 - 2-D Array")
print("2-D Array:")
print(two_d_array)
print("Dimensions:", two_d_array.ndim)  # Should print 2

# 3-D Arrays
three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nExample 2 - 3-D Array")
print("3-D Array:")
print(three_d_array)
print("Dimensions:", three_d_array.ndim)  # Should print 3

# Example 3: Check Number of Dimensions
# Test case 1
arr3 = np.array([[1, 2], [3, 4]])
print("\nExample 3 - Test case 1: Check Number of Dimensions")
print("Array:")
print(arr3)
print("Number of dimensions:", arr3.ndim)  # Should print 2

# Test case 2
arr4 = np.array([1, 2, 3, 4, 5], ndmin=5)
print("\nExample 3 - Test case 2: Check Number of Dimensions")
print("Higher dimensional array:")
print(arr4)
print("Number of dimensions:", arr4.ndim)  # Should print 5

# Example 4: Higher Dimensional Arrays
# Test case 1
high_dim_array1 = np.array([1, 2, 3, 4], ndmin=3)
print("\nExample 4 - Test case 1: Higher Dimensional Arrays")
print("3D Array created with ndmin=3:")
print(high_dim_array1)
print("Number of dimensions:", high_dim_array1.ndim)  # Should print 3

# Test case 2
high_dim_array2 = np.array([5, 6, 7, 8], ndmin=4)
print("\nExample 4 - Test case 2: Higher Dimensional Arrays")
print("4D Array created with ndmin=4:")
print(high_dim_array2)
print("Number of dimensions:", high_dim_array2.ndim)  # Should print 4

Example 1 - Test case 1: Create a NumPy ndarray Object
[1 2 3 4]
Type of arr1: <class 'numpy.ndarray'>

Example 1 - Test case 2: Create a NumPy ndarray Object
[10 20 30 40]
Type of arr2: <class 'numpy.ndarray'>

Example 2 - 0-D Array
0-D Array: 42
Dimensions: 0

Example 2 - 1-D Array
1-D Array: [ 5 10 15]
Dimensions: 1

Example 2 - 2-D Array
2-D Array:
[[1 2 3]
 [4 5 6]]
Dimensions: 2

Example 2 - 3-D Array
3-D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3

Example 3 - Test case 1: Check Number of Dimensions
Array:
[[1 2]
 [3 4]]
Number of dimensions: 2

Example 3 - Test case 2: Check Number of Dimensions
Higher dimensional array:
[[[[[1 2 3 4 5]]]]]
Number of dimensions: 5

Example 4 - Test case 1: Higher Dimensional Arrays
3D Array created with ndmin=3:
[[[1 2 3 4]]]
Number of dimensions: 3

Example 4 - Test case 2: Higher Dimensional Arrays
4D Array created with ndmin=4:
[[[[5 6 7 8]]]]
Number of dimensions: 4


In [32]:
# Description of inspiration for the function
"""
The function `sort_multi_dimensional_array` was inspired by the "NumPy Array Sorting" section.
I took inspiration from this section's focus on sorting arrays and expanded on it by adding conditional
checks to only sort arrays that are not already in order. This approach helps in understanding array
manipulation and the use of control structures like conditional statements and loops within NumPy.
"""

'\nThe function `sort_multi_dimensional_array` was inspired by the "NumPy Array Sorting" section.\nI took inspiration from this section\'s focus on sorting arrays and expanded on it by adding conditional\nchecks to only sort arrays that are not already in order. This approach helps in understanding array\nmanipulation and the use of control structures like conditional statements and loops within NumPy.\n'

In [25]:
print("I didn't find Brianna's Module.")

I didn't find Brianna's Module.


In [2]:
# File: example.py

import numpy as np

G = 6.6743e-11 # Gravitational contanst in m^3 kg^-1 s^-2

def escape_velocity(mass, radius):
    """
    Calculates escape velocity of a planet.
    v_esc = (2GM/r)^(1/2)

    Inputs:
    mass (float): mass of the planet in grams
    radius (float): radius of the planet in kg

    Output:
    esc_velocity (float): escape velocity in meters per second
    """
    
    result = 2 * G * mass
    result /= radius

    esc_velocity = np.sqrt(result)
    
    return esc_velocity

def orbital_velocity(mass, radius):
    """
    Calculates orbital velocity of a planet.
    v_orb = (GM/r)^(1/2)

    Inputs:
    mass (float): mass of the planet in kilograms
    radius (float): radius of the planet in meters

    Output:
    orb_velocity (float): orbital velocity in meters per second
    """

    orb_velocity = np.sqrt((G * mass) / radius)
    return orb_velocity


def rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet):
    """
    Determines if a rocket can escape based on its final velocity.

    Inputs:
    rocket_velocities (numpy.ndarray): list of rocket velocities in meters per second
    mass_of_planet (float): mass of the planet in kilograms
    radius_of_planet (float): radius of the planet in meters

    Output:
    statuses (list): statements for each rocket, describes its status.
    """

    esc_velocity = escape_velocity(mass = mass_of_planet,
                                      radius = radius_of_planet)
    
    orb_velocity = orbital_velocity(mass = mass_of_planet,
                                        radius = radius_of_planet)
    
    statuses = []
    for rocket in rocket_velocities:
        final_velocity_of_rocket = rocket[-1]
        
        if final_velocity_of_rocket < orb_velocity:
            statement = "Rocket crashes back into the planet!"
        
        elif orb_velocity <= final_velocity_of_rocket < esc_velocity:
            statement = "Rocket is orbiting around the planet."
        
        else:
            statement = "Rocket left the planet!"

        statuses.append(statement)

    return statuses

In [8]:
import numpy as np

G = 6.6743e-11  # Gravitational constant in m^3 kg^-1 s^-2

def escape_velocity(mass, radius):
    """
    Calculates escape velocity of a planet.
    """
    return np.sqrt(2 * G * mass / radius)

def orbital_velocity(mass, radius):
    """
    Calculates orbital velocity of a planet.
    """
    return np.sqrt(G * mass / radius)

def rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet):
    """
    Determines if a rocket can escape based on its final velocity.
    """
    esc_velocity = escape_velocity(mass=mass_of_planet, radius=radius_of_planet)
    orb_velocity = orbital_velocity(mass=mass_of_planet, radius=radius_of_planet)
    
    statuses = []
    for rocket in rocket_velocities:
        final_velocity_of_rocket = rocket[-1]
        
        if final_velocity_of_rocket < orb_velocity:
            statement = "Rocket crashes back into the planet!"
        elif orb_velocity <= final_velocity_of_rocket < esc_velocity:
            statement = "Rocket is orbiting around the planet."
        else:
            statement = "Rocket left the planet!"
        
        statuses.append(statement)
    
    return statuses

# Provided rocket velocities and planet data
rocket_velocities = np.array([
    [1000, 5000, 8000, 12000],  # Rocket 1's velocity at different times
    [2000, 6000, 9000, 10000],  # Rocket 2
    [3000, 3100, 3200, 3300]    # Rocket 3
])

mass_of_planet = 5.972e24  # Earth's mass in kilograms
radius_of_planet = 6.371e6  # Earth's radius in meters

# Calculate and print the statuses of the rockets
statuses = rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet)
print(statuses)

['Rocket left the planet!', 'Rocket is orbiting around the planet.', 'Rocket crashes back into the planet!']


In [10]:
# Description of good coding practices:
"""
The code follows good coding practices by using descriptive function and variable names, clear docstrings for each function, and leveraging NumPy for efficient mathematical calculations. It also uses conditional statements and loops effectively to determine the rocket statuses. However, there's room for improvement by adding error handling (e.g., checking for negative or invalid inputs) and breaking down the larger `rocket_launch` function into smaller, more modular functions to enhance readability and maintainability.
"""

"\nThe code follows good coding practices by using descriptive function and variable names, clear docstrings for each function, and leveraging NumPy for efficient mathematical calculations. It also uses conditional statements and loops effectively to determine the rocket statuses. However, there's room for improvement by adding error handling (e.g., checking for negative or invalid inputs) and breaking down the larger `rocket_launch` function into smaller, more modular functions to enhance readability and maintainability.\n"

In [22]:
# Description of the module:
"""
The module simulates projectile motion, allowing users to calculate the trajectory of a projectile based on its initial speed and launch angle. 
It includes functions to compute the velocity components, simulate the projectile’s path over time, find the maximum height reached, and classify the projectile based on its altitude. 
This module can be used to analyze and visualize projectile motion for physics-related applications.
"""

'\nThe module simulates projectile motion, allowing users to calculate the trajectory of a projectile based on its initial speed and launch angle. \nIt includes functions to compute the velocity components, simulate the projectile’s path over time, find the maximum height reached, and classify the projectile based on its altitude. \nThis module can be used to analyze and visualize projectile motion for physics-related applications.\n'

In [18]:
# Explanation of challenges and lessons learned:
"""
The most challenging part of building this module was ensuring that the simulation logic and the calculations were accurate, especially when working with multi-dimensional arrays and handling edge cases like when the projectile hits the ground. I learned the importance of using clear, modular functions to break down complex tasks, which improves code readability and reusability. This experience taught me how to better leverage NumPy for efficient computations, which I can apply to future projects involving data analysis or simulations.
"""

'\nThe most challenging part of building this module was ensuring that the simulation logic and the calculations were accurate, especially when working with multi-dimensional arrays and handling edge cases like when the projectile hits the ground. I learned the importance of using clear, modular functions to break down complex tasks, which improves code readability and reusability. This experience taught me how to better leverage NumPy for efficient computations, which I can apply to future projects involving data analysis or simulations.\n'

In [20]:
import numpy as np

# Constants
G = 6.6743e-11  # Gravitational constant in m^3 kg^-1 s^-2
g = 9.81  # Acceleration due to gravity (m/s^2)

def calculate_velocity(initial_velocity, angle):
    """
    Calculates the initial velocity components in the x and y directions.
    
    Inputs:
    - initial_velocity (float): The initial speed of the projectile in m/s.
    - angle (float): The launch angle in degrees.
    
    Outputs:
    - vel_x (float): Velocity in the x-direction.
    - vel_y (float): Velocity in the y-direction.
    """
    angle_rad = np.deg2rad(angle)  # Convert angle to radians
    vel_x = initial_velocity * np.cos(angle_rad)
    vel_y = initial_velocity * np.sin(angle_rad)
    return vel_x, vel_y

def simulate_projectile(initial_velocity, angle, time_steps):
    """
    Simulates projectile motion and returns the trajectory as a 2D array.
    
    Inputs:
    - initial_velocity (float): Initial speed in m/s.
    - angle (float): Launch angle in degrees.
    - time_steps (int): Number of time steps for the simulation.
    
    Outputs:
    - trajectory (ndarray): A 2D array containing time, x, and y positions.
    """
    vel_x, vel_y = calculate_velocity(initial_velocity, angle)
    trajectory = np.zeros((time_steps, 3))  # Create a multi-dimensional array

    for t in range(time_steps):
        time = t * 0.1  # Time interval of 0.1 seconds
        x_pos = vel_x * time
        y_pos = vel_y * time - 0.5 * g * time ** 2
        
        # Store the values in the trajectory array
        trajectory[t] = [time, x_pos, y_pos]
        
        # If the projectile hits the ground, stop the simulation
        if y_pos < 0:
            break

    return trajectory

def find_max_height(trajectory):
    """
    Finds the maximum height reached by the projectile.
    
    Inputs:
    - trajectory (ndarray): 2D array containing the projectile's trajectory.
    
    Output:
    - max_height (float): The maximum height in meters.
    """
    max_height = np.max(trajectory[:, 2])
    return max_height

def classify_projectile(trajectory):
    """
    Classifies the projectile based on its maximum height.
    
    Inputs:
    - trajectory (ndarray): 2D array of projectile motion data.
    
    Output:
    - classification (str): Description of the projectile's performance.
    """
    max_height = find_max_height(trajectory)
    
    if max_height > 50:
        classification = "High altitude projectile"
    elif max_height > 20:
        classification = "Moderate altitude projectile"
    else:
        classification = "Low altitude projectile"
    
    return classification

# Main code
if __name__ == "__main__":
    # Test cases
    initial_velocity = 50  # m/s
    angle = 45  # degrees
    time_steps = 100  # Number of time steps

    # Simulate projectile motion
    trajectory = simulate_projectile(initial_velocity, angle, time_steps)

    # Display the trajectory
    print("Time (s), X Position (m), Y Position (m):")
    print(trajectory)

    # Find the maximum height
    max_height = find_max_height(trajectory)
    print("\nMaximum Height:", max_height, "meters")

    # Classify the projectile
    classification = classify_projectile(trajectory)
    print("\nClassification:", classification)

Time (s), X Position (m), Y Position (m):
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e-01  3.53553391e+00  3.48648391e+00]
 [ 2.00000000e-01  7.07106781e+00  6.87486781e+00]
 [ 3.00000000e-01  1.06066017e+01  1.01651517e+01]
 [ 4.00000000e-01  1.41421356e+01  1.33573356e+01]
 [ 5.00000000e-01  1.76776695e+01  1.64514195e+01]
 [ 6.00000000e-01  2.12132034e+01  1.94474034e+01]
 [ 7.00000000e-01  2.47487373e+01  2.23452873e+01]
 [ 8.00000000e-01  2.82842712e+01  2.51450712e+01]
 [ 9.00000000e-01  3.18198052e+01  2.78467552e+01]
 [ 1.00000000e+00  3.53553391e+01  3.04503391e+01]
 [ 1.10000000e+00  3.88908730e+01  3.29558230e+01]
 [ 1.20000000e+00  4.24264069e+01  3.53632069e+01]
 [ 1.30000000e+00  4.59619408e+01  3.76724908e+01]
 [ 1.40000000e+00  4.94974747e+01  3.98836747e+01]
 [ 1.50000000e+00  5.30330086e+01  4.19967586e+01]
 [ 1.60000000e+00  5.65685425e+01  4.40117425e+01]
 [ 1.70000000e+00  6.01040764e+01  4.59286264e+01]
 [ 1.80000000e+00  6.36396103e+01  4.774